sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3307
    database: 
    username: 
    password: 

  alioss:
    endpoint: 
    access-key-id: 
    access-key-secret:
    bucket-name: 

  redis:
    host: localhost
    port: 6379
    database: 10

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  wechat:
    appid: 
    secret: 

  elasticsearch:
    uris: http://localhost:9200
    username: 
    password:



