sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: sky-mysql
    port: 3306
    database: sky_take_out
    username: root
    password: hhy760107

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNnD9tkdMNLaG8HxVQH
    access-key-secret: Mvm1x29M8OBQxpR1DxPav2hf4VoZSh
    bucket-name: cangqiong-haoyu

  redis:
    host: sky-redis
    port: 6379
    database: 10

  rabbitmq:
    host: sky-rabbitmq
    port: 5672
    username: guest
    password: guest

  wechat:
    appid: wx0355feeed4115f50
    secret: b4dad98427a9f8f8bf5dc509e6cdfbbe

  elasticsearch:
    uris: http://sky-elasticsearch:9200
    username: 
    password:

  

# Docker环境特定配置
logging:
  level:
    root: INFO
    com.sky: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

# Spring Elasticsearch配置
spring:
  elasticsearch:
    uris: http://sky-elasticsearch:9200
    connection-timeout: 5s
    socket-timeout: 30s 

  springfox:
    documentation:
      enabled: false