sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: sky-mysql
    port: 3306
    database: 
    username: 
    password: 

  alioss:
    endpoint: 
    access-key-id: 
    access-key-secret: 
    bucket-name: 

  redis:
    host: sky-redis
    port: 6379
    database: 10

  rabbitmq:
    host: sky-rabbitmq
    port: 5672
    username: 
    password: 

  wechat:
    appid: 
    secret:

  elasticsearch:
    uris: http://sky-elasticsearch:9200
    username: 
    password:

  

# Docker环境特定配置
logging:
  level:
    root: INFO
    com.sky: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

# Spring Elasticsearch配置
spring:
  elasticsearch:
    uris: http://sky-elasticsearch:9200
    connection-timeout: 5s
    socket-timeout: 30s 

  springfox:
    documentation:
      enabled: false
